language: java
before_install: 
 - wget https://services.gradle.org/distributions/gradle-2.4-all.zip
 - unzip -q -o gradle-2.4-all.zip
 - export PATH="${BASEDIR}/gradle:2.4/bin:${PATH}"
 - cd VoxxyTwitter

#install: gradle assemble
#script: gradle test

install: gradle build
script: gradle check